UPDATE companies SET trade_name = 'ROMEO ALEJANDRO' WHERE tenant_id = 3 AND cuit = '30715562673' AND company_type = 'client';
UPDATE companies SET trade_name = 'BECARIA JORGE' WHERE tenant_id = 3 AND cuit = '30654727380' AND company_type = 'client';
UPDATE companies SET trade_name = 'Carlos Rodriguez' WHERE tenant_id = 3 AND cuit = '20132998206' AND company_type = 'client';
UPDATE companies SET trade_name = 'BLANCO MIGUEL ANGEL' WHERE tenant_id = 3 AND cuit = '20108500302' AND company_type = 'client';
UPDATE companies SET trade_name = 'Lopez Mazzini' WHERE tenant_id = 3 AND legal_name ILIKE 'Lopez Mazzini' AND company_type = 'client';
UPDATE companies SET trade_name = 'MARIO MARTIN MAZZINI' WHERE tenant_id = 3 AND cuit = '20312314178' AND company_type = 'client';
UPDATE companies SET trade_name = 'Mosca javier' WHERE tenant_id = 3 AND cuit = '23225683719' AND company_type = 'client';
UPDATE companies SET trade_name = 'Goyeneche Segundo' WHERE tenant_id = 3 AND legal_name ILIKE 'Montenovo' AND company_type = 'client';
UPDATE companies SET trade_name = 'Luis Alfredo Martin' WHERE tenant_id = 3 AND cuit = '20240104238' AND company_type = 'client';
UPDATE companies SET trade_name = 'Pancho Montovio' WHERE tenant_id = 3 AND cuit = '30715700189' AND company_type = 'client';
UPDATE companies SET trade_name = 'Pancho Montovio' WHERE tenant_id = 3 AND cuit = '30716311771' AND company_type = 'client';
UPDATE companies SET trade_name = 'Santiago Camps' WHERE tenant_id = 3 AND cuit = '30715788086' AND company_type = 'client';
UPDATE companies SET trade_name = 'Pepe Marquez' WHERE tenant_id = 3 AND legal_name ILIKE 'El Retiro SA' AND company_type = 'client';
UPDATE companies SET trade_name = 'ROMULO' WHERE tenant_id = 3 AND legal_name ILIKE 'Romulo Andreucci' AND company_type = 'client';
UPDATE companies SET trade_name = 'Tato' WHERE tenant_id = 3 AND cuit = '20046972814' AND company_type = 'client';
UPDATE companies SET trade_name = 'Mauricio compras' WHERE tenant_id = 3 AND legal_name ILIKE 'Argenmilla' AND company_type = 'client';
UPDATE companies SET trade_name = 'Eric Cassels' WHERE tenant_id = 3 AND legal_name ILIKE 'Invagro SRL' AND company_type = 'client';
UPDATE companies SET trade_name = 'pablo' WHERE tenant_id = 3 AND legal_name ILIKE 'Pablo San Juan' AND company_type = 'client';
UPDATE companies SET trade_name = 'Juan Campion' WHERE tenant_id = 3 AND legal_name ILIKE 'SEIS HNOS SRL' AND company_type = 'client';
UPDATE companies SET trade_name = 'Marcos/Agustin' WHERE tenant_id = 3 AND legal_name ILIKE 'Ganagrin SA Agricola Ganadera' AND company_type = 'client';
UPDATE companies SET trade_name = 'sergio' WHERE tenant_id = 3 AND legal_name ILIKE 'Agropecuaria Dos Hermanos SA' AND company_type = 'client';
UPDATE companies SET trade_name = 'Juan MartinPerkins' WHERE tenant_id = 3 AND legal_name ILIKE 'Suava SA' AND company_type = 'client';
UPDATE companies SET trade_name = 'pablo' WHERE tenant_id = 3 AND legal_name ILIKE 'Pablo Slavskis' AND company_type = 'client';
UPDATE companies SET trade_name = 'Ramiro Marban' WHERE tenant_id = 3 AND cuit = '30711038565' AND company_type = 'client';
UPDATE companies SET trade_name = 'Patricio' WHERE tenant_id = 3 AND legal_name ILIKE 'SYD LAFUENTE' AND company_type = 'client';
UPDATE companies SET trade_name = 'Tato Games' WHERE tenant_id = 3 AND legal_name ILIKE 'Narciso J Muñoz SA' AND company_type = 'client';
UPDATE companies SET trade_name = 'Carlos' WHERE tenant_id = 3 AND legal_name ILIKE 'Carlitos Marote' AND company_type = 'client';
UPDATE companies SET trade_name = 'Joaquin/Francisco' WHERE tenant_id = 3 AND legal_name ILIKE 'La Achicoria Agro SA' AND company_type = 'client';
UPDATE companies SET trade_name = 'Santiago/Chaca' WHERE tenant_id = 3 AND legal_name ILIKE 'Virreyes Agropecuaria SA' AND company_type = 'client';
UPDATE companies SET trade_name = 'Domingo Irigaray' WHERE tenant_id = 3 AND legal_name ILIKE 'Agropecuaria La Constancia SA' AND company_type = 'client';
UPDATE companies SET trade_name = 'Daniel' WHERE tenant_id = 3 AND legal_name ILIKE 'Curuchet Daniel Oscar' AND company_type = 'client';
UPDATE companies SET trade_name = 'Adrian' WHERE tenant_id = 3 AND legal_name ILIKE 'Fernandez Carlos Adrian' AND company_type = 'client';
UPDATE companies SET trade_name = 'Eduardo Otero' WHERE tenant_id = 3 AND cuit = '30508692648' AND company_type = 'client';
UPDATE companies SET trade_name = 'Luz' WHERE tenant_id = 3 AND legal_name ILIKE 'Ranchito Maria Ines SAU' AND company_type = 'client';
UPDATE companies SET trade_name = 'Nicolas Farrando' WHERE tenant_id = 3 AND legal_name ILIKE 'Trovarelli Graciela Viviana' AND company_type = 'client';
UPDATE companies SET trade_name = 'Manuel' WHERE tenant_id = 3 AND cuit = '30692280233' AND company_type = 'client';
UPDATE companies SET trade_name = 'Ramiro' WHERE tenant_id = 3 AND cuit = '30693481763' AND company_type = 'client';
UPDATE companies SET trade_name = 'Domingo Irigaray' WHERE tenant_id = 3 AND cuit = '30711586691' AND company_type = 'client';
UPDATE companies SET trade_name = 'Pato Estruch' WHERE tenant_id = 3 AND cuit = '33666648809' AND company_type = 'client';
UPDATE companies SET trade_name = 'Jose Airasca' WHERE tenant_id = 3 AND cuit = '20245855967' AND company_type = 'client';
UPDATE companies SET trade_name = 'JOSE MOURIÑO' WHERE tenant_id = 3 AND cuit = '30555563295' AND company_type = 'client';
UPDATE companies SET trade_name = 'Juan' WHERE tenant_id = 3 AND cuit = '20119133271' AND company_type = 'client';
UPDATE companies SET trade_name = 'Patricio Trezeguet' WHERE tenant_id = 3 AND cuit = '30582316941' AND company_type = 'client';
UPDATE companies SET trade_name = 'Jose/Clemente' WHERE tenant_id = 3 AND cuit = '20148949477' AND company_type = 'client';
UPDATE companies SET trade_name = 'Martin Miguez' WHERE tenant_id = 3 AND cuit = '30714559768' AND company_type = 'client';
UPDATE companies SET trade_name = 'Marcelo Silva' WHERE tenant_id = 3 AND cuit = '30718106288' AND company_type = 'client';
UPDATE companies SET trade_name = 'Baltasar Gutierrez' WHERE tenant_id = 3 AND cuit = '30509755813' AND company_type = 'client';
UPDATE companies SET trade_name = 'Juan Pedro A' WHERE tenant_id = 3 AND cuit = '20309605358' AND company_type = 'client';
UPDATE companies SET trade_name = 'Juan Moreno' WHERE tenant_id = 3 AND cuit = '27055851501' AND company_type = 'client';
UPDATE companies SET trade_name = 'Lucas Lennon' WHERE tenant_id = 3 AND cuit = '30708344717' AND company_type = 'client';
UPDATE companies SET trade_name = 'Segundo Goyeneche' WHERE tenant_id = 3 AND cuit = '30714704628' AND company_type = 'client';
UPDATE companies SET trade_name = 'Lucas Lennon' WHERE tenant_id = 3 AND cuit = '30711383030' AND company_type = 'client';
UPDATE companies SET trade_name = 'Manuel Madero' WHERE tenant_id = 3 AND cuit = '30623758253' AND company_type = 'client';
UPDATE companies SET trade_name = 'Marcelo Guardo' WHERE tenant_id = 3 AND cuit = '30715496727' AND company_type = 'client';
UPDATE companies SET trade_name = 'Juan Manuel Azumendi' WHERE tenant_id = 3 AND cuit = '30513236243' AND company_type = 'client';
UPDATE companies SET trade_name = 'Maria Pelaez' WHERE tenant_id = 3 AND cuit = '30694305365' AND company_type = 'client';
UPDATE companies SET trade_name = 'Walter' WHERE tenant_id = 3 AND cuit = '20050430066' AND company_type = 'client';
UPDATE companies SET trade_name = 'Clemente Ballerio' WHERE tenant_id = 3 AND cuit = '30666652580' AND company_type = 'client';
UPDATE companies SET trade_name = 'Juan Campion' WHERE tenant_id = 3 AND cuit = '20169446556' AND company_type = 'client';
UPDATE companies SET trade_name = 'Pancho Berisso' WHERE tenant_id = 3 AND cuit = '30688956427' AND company_type = 'client';
UPDATE companies SET trade_name = 'Santiago Galindez' WHERE tenant_id = 3 AND cuit = '20184058554' AND company_type = 'client';
UPDATE companies SET trade_name = 'CECOTTI FERNANDO JORGE' WHERE tenant_id = 3 AND cuit = '20362592950' AND company_type = 'client';
UPDATE companies SET trade_name = 'JAVIER ROMA' WHERE tenant_id = 3 AND cuit = '30708522275' AND company_type = 'client';
UPDATE companies SET trade_name = 'osvaldo' WHERE tenant_id = 3 AND cuit = '33710355989' AND company_type = 'client';
UPDATE companies SET trade_name = 'Gaston' WHERE tenant_id = 3 AND cuit = '30654965273' AND company_type = 'client';
UPDATE companies SET trade_name = 'Aldo' WHERE tenant_id = 3 AND cuit = '30707584579' AND company_type = 'client';
UPDATE companies SET trade_name = 'MARTIN' WHERE tenant_id = 3 AND cuit = '20239342982' AND company_type = 'client';
UPDATE companies SET trade_name = 'Juan Martin' WHERE tenant_id = 3 AND legal_name ILIKE 'Capelle Juan Martin' AND company_type = 'client';
UPDATE companies SET trade_name = 'Emillio' WHERE tenant_id = 3 AND legal_name ILIKE 'El pecan' AND company_type = 'client';
UPDATE companies SET trade_name = 'anibal' WHERE tenant_id = 3 AND legal_name ILIKE 'Lagreca Anibal' AND company_type = 'client';
UPDATE companies SET trade_name = 'LEGNANI J. Miguel Carmelo' WHERE tenant_id = 3 AND cuit = '20334797431' AND company_type = 'client';
UPDATE companies SET trade_name = 'ALEJANDRO' WHERE tenant_id = 3 AND legal_name ILIKE 'Mendia Alejandro' AND company_type = 'client';
UPDATE companies SET trade_name = 'RUBEN' WHERE tenant_id = 3 AND legal_name ILIKE 'Monasterio Ruben' AND company_type = 'client';
UPDATE companies SET trade_name = 'PALA' WHERE tenant_id = 3 AND cuit = '30710229542' AND company_type = 'client';
UPDATE companies SET trade_name = 'IGNACIO' WHERE tenant_id = 3 AND cuit = '30717237052' AND company_type = 'client';
UPDATE companies SET trade_name = 'JUAN ESTEBAN' WHERE tenant_id = 3 AND cuit = '23170966619' AND company_type = 'client';
UPDATE companies SET trade_name = 'MARCELO' WHERE tenant_id = 3 AND cuit = '30532275357' AND company_type = 'client';
UPDATE companies SET trade_name = 'German' WHERE tenant_id = 3 AND cuit = '30610312949' AND company_type = 'client';
UPDATE companies SET trade_name = 'Ricardo/ Santiago' WHERE tenant_id = 3 AND cuit = '20121846757' AND company_type = 'client';
UPDATE companies SET trade_name = 'agrop. madre selva' WHERE tenant_id = 3 AND legal_name ILIKE 'Santamaria Matias' AND company_type = 'client';
UPDATE companies SET trade_name = 'MARIANO' WHERE tenant_id = 3 AND cuit = '20269068753' AND company_type = 'client';
UPDATE companies SET trade_name = 'EUGENIO' WHERE tenant_id = 3 AND cuit = '30527692659' AND company_type = 'client';
UPDATE companies SET trade_name = 'CARLOS' WHERE tenant_id = 3 AND cuit = '20121846331' AND company_type = 'client';
UPDATE companies SET trade_name = 'CARLOS' WHERE tenant_id = 3 AND cuit = '27166236989' AND company_type = 'client';
UPDATE companies SET trade_name = 'Juan' WHERE tenant_id = 3 AND cuit = '20341178429' AND company_type = 'client';
UPDATE companies SET trade_name = 'JULIAN' WHERE tenant_id = 3 AND cuit = '30665376431' AND company_type = 'client';
UPDATE companies SET trade_name = 'JOSE' WHERE tenant_id = 3 AND cuit = '30710224753' AND company_type = 'client';
UPDATE companies SET trade_name = 'GUSTAVO' WHERE tenant_id = 3 AND cuit = '30715482912' AND company_type = 'client';
UPDATE companies SET trade_name = 'RICARDO' WHERE tenant_id = 3 AND cuit = '30716776693' AND company_type = 'client';
UPDATE companies SET trade_name = 'GUSTAVO' WHERE tenant_id = 3 AND cuit = '30713710500' AND company_type = 'client';
UPDATE companies SET trade_name = 'ESTEBAN' WHERE tenant_id = 3 AND cuit = '20123861419' AND company_type = 'client';
UPDATE companies SET trade_name = 'pablo' WHERE tenant_id = 3 AND cuit = '30711031436' AND company_type = 'client';
UPDATE companies SET trade_name = 'MARCELO' WHERE tenant_id = 3 AND cuit = '33711216249' AND company_type = 'client';
UPDATE companies SET trade_name = 'Tato' WHERE tenant_id = 3 AND cuit = '30716738260' AND company_type = 'client';
UPDATE companies SET trade_name = 'Grossi Bruno' WHERE tenant_id = 3 AND cuit = '23050661849' AND company_type = 'client';
UPDATE companies SET trade_name = 'Grossi Bruno' WHERE tenant_id = 3 AND cuit = '30716579030' AND company_type = 'client';
UPDATE companies SET trade_name = 'Ferrari Gustavo' WHERE tenant_id = 3 AND cuit = '20165794177' AND company_type = 'client';
UPDATE companies SET trade_name = 'Martin' WHERE tenant_id = 3 AND cuit = '20054002298' AND company_type = 'client';
UPDATE companies SET trade_name = 'Pedro' WHERE tenant_id = 3 AND legal_name ILIKE 'PEDRO MUNDIÑANO' AND company_type = 'client';
UPDATE companies SET trade_name = 'Pedro' WHERE tenant_id = 3 AND cuit = '30717774333' AND company_type = 'client';
UPDATE companies SET trade_name = 'Walter' WHERE tenant_id = 3 AND cuit = '23233070629' AND company_type = 'client';
UPDATE companies SET trade_name = 'Lucas Semper' WHERE tenant_id = 3 AND cuit = '30586102776' AND company_type = 'client';
UPDATE companies SET trade_name = 'Ignacio GQuesnel' WHERE tenant_id = 3 AND cuit = '30509377363' AND company_type = 'client';
UPDATE companies SET trade_name = 'JOSE' WHERE tenant_id = 3 AND legal_name ILIKE 'JOSE BRAVO' AND company_type = 'client';
UPDATE companies SET trade_name = 'Horacio' WHERE tenant_id = 3 AND cuit = '20115778502' AND company_type = 'client';
UPDATE companies SET trade_name = 'Carolina' WHERE tenant_id = 3 AND cuit = '20100958636' AND company_type = 'client';
UPDATE companies SET trade_name = 'Laura' WHERE tenant_id = 3 AND legal_name ILIKE 'LAURA MASSOLA' AND company_type = 'client';
UPDATE companies SET trade_name = 'Cecilia Pereyra Iraola' WHERE tenant_id = 3 AND cuit = '30525897067' AND company_type = 'client';
UPDATE companies SET trade_name = 'Gonzalo' WHERE tenant_id = 3 AND cuit = '33579328199' AND company_type = 'client';
UPDATE companies SET trade_name = 'Adrian' WHERE tenant_id = 3 AND cuit = '20177277585' AND company_type = 'client';
UPDATE companies SET trade_name = 'Cesar' WHERE tenant_id = 3 AND cuit = '20215263135' AND company_type = 'client';
UPDATE companies SET trade_name = 'Vanina' WHERE tenant_id = 3 AND cuit = '20281921267' AND company_type = 'client';
UPDATE companies SET trade_name = 'Lujan' WHERE tenant_id = 3 AND cuit = '23128957944' AND company_type = 'client';
UPDATE companies SET trade_name = 'Juan Carlos' WHERE tenant_id = 3 AND cuit = '30715101765' AND company_type = 'client';
UPDATE companies SET trade_name = 'Martin' WHERE tenant_id = 3 AND cuit = '20297729609' AND company_type = 'client';
UPDATE companies SET trade_name = 'Nahir' WHERE tenant_id = 3 AND cuit = '30509285302' AND company_type = 'client';
UPDATE companies SET trade_name = 'Luis' WHERE tenant_id = 3 AND cuit = '30666659682' AND company_type = 'client';
UPDATE companies SET trade_name = 'Carmelo' WHERE tenant_id = 3 AND cuit = '20050555101' AND company_type = 'client';
UPDATE companies SET trade_name = 'Juan' WHERE tenant_id = 3 AND cuit = '30716714302' AND company_type = 'client';
UPDATE companies SET trade_name = 'EZEQUIEL' WHERE tenant_id = 3 AND cuit = '27298260013' AND company_type = 'client';
UPDATE companies SET trade_name = 'Juan' WHERE tenant_id = 3 AND cuit = '20312999782' AND company_type = 'client';
UPDATE companies SET trade_name = 'FRANCISCO' WHERE tenant_id = 3 AND cuit = '30717649083' AND company_type = 'client';
UPDATE companies SET trade_name = 'MARIO' WHERE tenant_id = 3 AND cuit = '20120306635' AND company_type = 'client';
UPDATE companies SET trade_name = 'NORA' WHERE tenant_id = 3 AND cuit = '30635037268' AND company_type = 'client';
UPDATE companies SET trade_name = 'Miguel' WHERE tenant_id = 3 AND cuit = '20145629374' AND company_type = 'client';
UPDATE companies SET trade_name = 'Hernan' WHERE tenant_id = 3 AND cuit = '30716419858' AND company_type = 'client';
UPDATE companies SET trade_name = 'Aldo - Mauro' WHERE tenant_id = 3 AND cuit = '30715219960' AND company_type = 'client';
UPDATE companies SET trade_name = 'Aldo - Mauro' WHERE tenant_id = 3 AND cuit = '30710027079' AND company_type = 'client';
UPDATE companies SET trade_name = 'Agustin Fernandez' WHERE tenant_id = 3 AND cuit = '30716079062' AND company_type = 'client';
UPDATE companies SET trade_name = 'NORA' WHERE tenant_id = 3 AND cuit = '27209817867' AND company_type = 'client';
UPDATE companies SET trade_name = 'Eduardo-Carlos' WHERE tenant_id = 3 AND cuit = '30715748009' AND company_type = 'client';
UPDATE companies SET trade_name = 'Eduardo-Carlos' WHERE tenant_id = 3 AND cuit = '30666652033' AND company_type = 'client';
UPDATE companies SET trade_name = 'Nazareno' WHERE tenant_id = 3 AND cuit = '33709894329' AND company_type = 'client';
UPDATE companies SET trade_name = 'Daniel Lamattina' WHERE tenant_id = 3 AND cuit = '27125674114' AND company_type = 'client';
UPDATE companies SET trade_name = 'Martin Garat' WHERE tenant_id = 3 AND cuit = '30508572057' AND company_type = 'client';
UPDATE companies SET trade_name = 'Carlos' WHERE tenant_id = 3 AND cuit = '20241465080' AND company_type = 'client';
UPDATE companies SET trade_name = 'WAGNER' WHERE tenant_id = 3 AND cuit = '20940880875' AND company_type = 'client';
UPDATE companies SET trade_name = 'Pedro' WHERE tenant_id = 3 AND cuit = '20121777445' AND company_type = 'client';
UPDATE companies SET trade_name = 'Pablo' WHERE tenant_id = 3 AND cuit = '20242199708' AND company_type = 'client';
UPDATE companies SET trade_name = 'Nicolas' WHERE tenant_id = 3 AND cuit = '30708063645' AND company_type = 'client';
UPDATE companies SET trade_name = 'Agustin' WHERE tenant_id = 3 AND cuit = '30687234991' AND company_type = 'client';
UPDATE companies SET trade_name = 'Nahir' WHERE tenant_id = 3 AND cuit = '30509285302' AND company_type = 'client';
UPDATE companies SET trade_name = 'Mariano Chiaretta' WHERE tenant_id = 3 AND cuit = '30709878421' AND company_type = 'client';
UPDATE companies SET trade_name = 'Sebastian De Ocampo' WHERE tenant_id = 3 AND cuit = '30561787243' AND company_type = 'client';
UPDATE companies SET trade_name = 'Juan Carlos' WHERE tenant_id = 3 AND cuit = '30582522177' AND company_type = 'client';
UPDATE companies SET trade_name = 'Janeiro Gabriel' WHERE tenant_id = 3 AND legal_name ILIKE 'Rangi Agropecuaria' AND company_type = 'client';
UPDATE companies SET trade_name = 'Benjamin - Mauricio Francia' WHERE tenant_id = 3 AND legal_name ILIKE '4 leguas' AND company_type = 'client';
UPDATE companies SET trade_name = 'pablo aristi' WHERE tenant_id = 3 AND cuit = '30707882243' AND company_type = 'client';
UPDATE companies SET trade_name = 'AGRAR AGRICOLA ARGENTINA S A' WHERE tenant_id = 3 AND cuit = '30594231119' AND company_type = 'client';
UPDATE companies SET trade_name = 'ALFARO EDUARDO FEDERICO' WHERE tenant_id = 3 AND cuit = '20082505297' AND company_type = 'client';
UPDATE companies SET trade_name = 'ARANA RAUL ALBERTO' WHERE tenant_id = 3 AND cuit = '20140855309' AND company_type = 'client';
UPDATE companies SET trade_name = 'WILSON JORGE' WHERE tenant_id = 3 AND legal_name ILIKE 'WILSON JORGE' AND company_type = 'client';
UPDATE companies SET trade_name = 'mauricio' WHERE tenant_id = 3 AND cuit = '20286018875' AND company_type = 'client';
UPDATE companies SET trade_name = 'BAUSCHEN BERNARDO' WHERE tenant_id = 3 AND cuit = '20280996271' AND company_type = 'client';
UPDATE companies SET trade_name = 'GERARDO' WHERE tenant_id = 3 AND cuit = '20145933456' AND company_type = 'client';
UPDATE companies SET trade_name = 'Manuel  Morales' WHERE tenant_id = 3 AND cuit = '20049775041' AND company_type = 'client';
UPDATE companies SET trade_name = 'DEMATTEIS OSCAR' WHERE tenant_id = 3 AND cuit = '30708925167' AND company_type = 'client';
UPDATE companies SET trade_name = 'HUGO COLOMBO' WHERE tenant_id = 3 AND cuit = '30711917744' AND company_type = 'client';
UPDATE companies SET trade_name = 'JOSE RICARDO KLIN' WHERE tenant_id = 3 AND legal_name ILIKE 'JOSE RICARDO KLIN' AND company_type = 'client';
UPDATE companies SET trade_name = 'MOLEA JUAN HECTOR' WHERE tenant_id = 3 AND legal_name ILIKE 'MOLEA JORGE Y RAUL' AND company_type = 'client';
UPDATE companies SET trade_name = 'DANIEL VALENTINO' WHERE tenant_id = 3 AND cuit = '27306282323' AND company_type = 'client';
