UPDATE companies SET trade_name = 'Fernando' WHERE tenant_id = 3 AND legal_name ILIKE 'Fernando Barich' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'CARRANO ERIEL' WHERE tenant_id = 3 AND cuit = '30709330329' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'JAIME PE�A .' WHERE tenant_id = 3 AND cuit = '27002251723' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'BARETA PEDRO' WHERE tenant_id = 3 AND cuit = '20121757290' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Mario Barni' WHERE tenant_id = 3 AND cuit = '20204910120' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'BARNI WALTER' WHERE tenant_id = 3 AND cuit = '20229342976' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'MARIANA DEMCZUK' WHERE tenant_id = 3 AND cuit = '27008539257' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'beccaria ana clara' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Brollo Marcelo' WHERE tenant_id = 3 AND cuit = '20241940757' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'CAPURRO EDGARDOTOMAS TUR DECIDE' WHERE tenant_id = 3 AND cuit = '20050088805' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Carretoni Elvio' WHERE tenant_id = 3 AND cuit = '20139570430' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'DANIEL CARRIZO' WHERE tenant_id = 3 AND cuit = '20123239653' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'ERNESTO DE GRACIA' WHERE tenant_id = 3 AND cuit = '20050646115' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'NICOLAS GIULIANI' WHERE tenant_id = 3 AND cuit = '24049779573' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'PABLO GOROSTIAGUE' WHERE tenant_id = 3 AND cuit = '20107836587' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Aldo Marco' WHERE tenant_id = 3 AND cuit = '30707208909' AND company_type = 'prospect';
UPDATE companies SET trade_name = '"ROSSI WALTER ""TOTO"""' WHERE tenant_id = 3 AND cuit = '27060732278' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Rodolfo Lapietra' WHERE tenant_id = 3 AND cuit = '30665559080' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'HECTOR DUVILLE' WHERE tenant_id = 3 AND cuit = '30526615618' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'SERGIO MOLEA' WHERE tenant_id = 3 AND cuit = '30709206733' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'FEDERICO MARCO' WHERE tenant_id = 3 AND cuit = '30709275328' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'MARRA JUAN' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'DANIEL MAZZINI' WHERE tenant_id = 3 AND cuit = '20119702837' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'ALDO PENELLA' WHERE tenant_id = 3 AND cuit = '30708315857' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'JOSE LUIS PASTORI' WHERE tenant_id = 3 AND cuit = '27105622878' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'OIZA CLAUDIO' WHERE tenant_id = 3 AND cuit = '20234437470' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'PIRONIO MATIAS' WHERE tenant_id = 3 AND cuit = '20050550843' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'PIRONIO MARIO' WHERE tenant_id = 3 AND cuit = '20050632572' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'SAMPAOLESI AUGUSTO' WHERE tenant_id = 3 AND cuit = '20050127258' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Facuando Medina' WHERE tenant_id = 3 AND cuit = '30716122278' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'ROMEO ALEJANDRO' WHERE tenant_id = 3 AND legal_name ILIKE 'SCHMIDT ADRIANA' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'sio ricardo' WHERE tenant_id = 3 AND cuit = '30709024112' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'TEL DE FABIO SOCIO DE SP�SITO JOSE' WHERE tenant_id = 3 AND cuit = '20114219860' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'STEIMBERG CARLOS' WHERE tenant_id = 3 AND cuit = '20045503632' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'TENORIO ANGEL' WHERE tenant_id = 3 AND cuit = '20125133321' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'TENORIO HUGO, EDUARDO Y ANGEL' WHERE tenant_id = 3 AND cuit = '20147766298' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'URRICELQUI DANIEL' WHERE tenant_id = 3 AND cuit = '20102382820' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Vaccaro Mariano' WHERE tenant_id = 3 AND cuit = '30709845094' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'LA CRIOLLA' WHERE tenant_id = 3 AND legal_name ILIKE 'MAXIMILIANO SOSA MI�O' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Maxi' WHERE tenant_id = 3 AND legal_name ILIKE 'Maxi Heidckamp' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Valeria' WHERE tenant_id = 3 AND legal_name ILIKE 'Garbers Valeria' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Julian Diaz' WHERE tenant_id = 3 AND legal_name ILIKE 'Fernando Diaz' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Juan Carlos' WHERE tenant_id = 3 AND legal_name ILIKE 'Juan Carlos Paganini' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'pablo' WHERE tenant_id = 3 AND legal_name ILIKE 'Pablo Matias' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Marcos' WHERE tenant_id = 3 AND legal_name ILIKE 'Marcos Scroffa' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Carlos/Lisa' WHERE tenant_id = 3 AND legal_name ILIKE 'Carlos Duthie' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'pablo' WHERE tenant_id = 3 AND legal_name ILIKE 'Pablo Amezcua' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Santiago' WHERE tenant_id = 3 AND legal_name ILIKE 'Blousson Santiago' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Esteban' WHERE tenant_id = 3 AND legal_name ILIKE 'Esteban Churrupit' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'I�aki/Marcos' WHERE tenant_id = 3 AND legal_name ILIKE 'El Bravaje SA' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Juan' WHERE tenant_id = 3 AND legal_name ILIKE 'Juan M Cozzarin' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Simon' WHERE tenant_id = 3 AND legal_name ILIKE 'Los Indios' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Gonzalo' WHERE tenant_id = 3 AND legal_name ILIKE 'Gonzalo Gamboa' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'pablo' WHERE tenant_id = 3 AND legal_name ILIKE 'Pablo Baratussi' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Marcos' WHERE tenant_id = 3 AND legal_name ILIKE 'Marcos Etulain' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Joaquin/Fermin' WHERE tenant_id = 3 AND legal_name ILIKE 'Joaquin Bader' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Joaquin Ibarbia' WHERE tenant_id = 3 AND legal_name ILIKE 'Est. Agrop. San Jorge' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Nicolas/Marcos' WHERE tenant_id = 3 AND legal_name ILIKE 'Nicolas Radnic' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Cristian' WHERE tenant_id = 3 AND legal_name ILIKE 'Cristian Sundblad' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'pablo' WHERE tenant_id = 3 AND legal_name ILIKE 'Alemano Pablo' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Augusto Maquieria' WHERE tenant_id = 3 AND legal_name ILIKE 'Aumaq Agro SA' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Cochi' WHERE tenant_id = 3 AND legal_name ILIKE 'Cochi Moretti' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Luis Maria Rollero' WHERE tenant_id = 3 AND legal_name ILIKE 'Dos Marias' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Norberto' WHERE tenant_id = 3 AND legal_name ILIKE 'Degiovanangelo Marcelo' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Norberto' WHERE tenant_id = 3 AND legal_name ILIKE 'Degiovanangelo Norberto' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'FRANCISCO' WHERE tenant_id = 3 AND legal_name ILIKE 'Pereyra SAAI' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Rossi GASTON' WHERE tenant_id = 3 AND legal_name ILIKE 'Agro Rossi' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'MARTINEAU RENE' WHERE tenant_id = 3 AND cuit = '30612489005' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'BONO DARIO LO VE JUANMA EL 4/7' WHERE tenant_id = 3 AND cuit = '30709547158' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND cuit = '20102557485' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Valentin Bracco' WHERE tenant_id = 3 AND cuit = '20370331791' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Alejandro Monteverde' WHERE tenant_id = 3 AND cuit = '30541289433' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Marco Federico' WHERE tenant_id = 3 AND cuit = '30708420502' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'ROSSI DELIA' WHERE tenant_id = 3 AND cuit = '33662105959' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'RAUL CATALAN PELET' WHERE tenant_id = 3 AND cuit = '30606117767' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'PABLO PAEZ' WHERE tenant_id = 3 AND cuit = '30714006238' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'MARTIN' WHERE tenant_id = 3 AND cuit = '30718034759' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Jose Luis Iglesias' WHERE tenant_id = 3 AND cuit = '30707891013' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Perningotti Carlos' WHERE tenant_id = 3 AND cuit = '30708574585' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Alfredo Latorre' WHERE tenant_id = 3 AND cuit = '20258393822' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Moreno Alberto' WHERE tenant_id = 3 AND cuit = '30632000304' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'VICTOR Pedemonte' WHERE tenant_id = 3 AND cuit = '30658255491' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'PESTA�A MAURO' WHERE tenant_id = 3 AND cuit = '20291727760' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Gonzalo' WHERE tenant_id = 3 AND cuit = '20227118041' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'BECCARIA ANA CLARA' WHERE tenant_id = 3 AND cuit = '30712140980' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Repeto Arnaldo' WHERE tenant_id = 3 AND cuit = '30507751748' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'mauricio' WHERE tenant_id = 3 AND cuit = '20285619131' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Bernardo Bauschen' WHERE tenant_id = 3 AND cuit = '20241598269' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'ALFREDO ROSSI' WHERE tenant_id = 3 AND cuit = '30620681500' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Rossi GASTON' WHERE tenant_id = 3 AND cuit = '20050361021' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'ROSSI MARTIN' WHERE tenant_id = 3 AND cuit = '20050382215' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'RUIZ CARLOS' WHERE tenant_id = 3 AND cuit = '23050665909' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Tagliaferro Pedro' WHERE tenant_id = 3 AND cuit = '20169185345' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'FERRANDO ENRIQUE' WHERE tenant_id = 3 AND cuit = '30511801849' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'ANDRES STARC ASESOR DE MARCOS GALPARIN' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'DIEGO' WHERE tenant_id = 3 AND legal_name ILIKE 'Abad Diego' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Sara' WHERE tenant_id = 3 AND legal_name ILIKE 'Argiroz Sara' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'sergio' WHERE tenant_id = 3 AND legal_name ILIKE 'Asencio Sergio' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Santiago' WHERE tenant_id = 3 AND legal_name ILIKE 'Bastarrica Santiago' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'javier' WHERE tenant_id = 3 AND cuit = '20101910246' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Santiago' WHERE tenant_id = 3 AND legal_name ILIKE 'Bolognia Santiago' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'tomas' WHERE tenant_id = 3 AND legal_name ILIKE 'Bond Tomas' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Brina Pedro' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Butti Beto' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Adrian Torres' WHERE tenant_id = 3 AND legal_name ILIKE 'Caba�a El volcan' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'caba�a la gaby' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Callebua Tomas' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Campos Luis' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Canepa Javier' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Canova Daniel' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Carretero Nicolas' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Carrillo Martin' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Casado Ignacio' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Castellani Norma' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Cattaneo carlos' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Cecilia M.' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Ramon Garcia' WHERE tenant_id = 3 AND legal_name ILIKE 'Centrigen Fernando' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Cestera Francisco' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Cirio Gustavo' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Cuello Franco' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'De Miguel Lucas' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Debernardi Ricardo' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Deluccia, indio' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Di Risio Raul' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Di Salvo Nicolas' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Diaz Arturo' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Diaz Miguel' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Doglioli Gino' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Doglioli Miguel' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Borrego Graciela' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Ega�a Miguel' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Ega�a Ramiro' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'paula' WHERE tenant_id = 3 AND legal_name ILIKE 'Eoisa Gustavo' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Eripa Juan Segundo' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Erreca Juan Carlos' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Espa�ol Gustavo' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Estallo Fermin' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Etulain, Marcos' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Fernandez Alejandro' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Ferrari jorge (pini)' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Ferreyra Hernan' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Ferro Javier' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Francisco tambero' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Frutos Francisco' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Fuentes Manuel' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Fuster Adrian' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Garcia Carlos' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Garin Jose' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Garrote Gustavo' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Gauna Mauricio' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Gayol Sergio' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Genari Alejandro' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Gilaberth Jorge' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Giovo Ricardo' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Grasano Roberto' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Guerrico Francisco' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Holgado I�aki' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Iglesias Rodolfo' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Iturriaga Mariano' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Juarros Marcos' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Kesnell Ignacio' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'pablo' WHERE tenant_id = 3 AND legal_name ILIKE 'la fuyi/ la sorpresa' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Landaburru Pino' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Larrondo Paula' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'MARCELO' WHERE tenant_id = 3 AND legal_name ILIKE 'LAS DELICIAS' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Lasserre Fernando' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Laurnagaray I�aki' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Lezica Gustavo' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Lopez Emilio' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Manfredi Federico' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Manso Juan Alberto' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Mapis Juan Manuel' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Maquieira Augusto' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Marinucci Mariano' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Martin, Fausto(leopoldo)' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Mas Nestor' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'SUC. de German Alvarez' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Mendi Juan' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Merello Roberto' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Miglerina Martin' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Mignaquy Sebastian' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Minicchello Cristian' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Mogni Mario Jose(GUCHO)' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'JULIAN' WHERE tenant_id = 3 AND legal_name ILIKE 'Molina Julian' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Montero Juani' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Moran Oscar' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Mosquera Eduardo' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Mussio Franco' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Ninni Miguel' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Ochoa Marina' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Odriozola Alvaro' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Odriozola Mateo' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Ordinas Marcelo' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Otero Sergio' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Otonello Alfredo' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Ovin Enzo' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Santiago' WHERE tenant_id = 3 AND legal_name ILIKE 'Peralta Santiago,' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Perez Carlos, el abu' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Miguel' WHERE tenant_id = 3 AND legal_name ILIKE 'Pettinari Miguel' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Pfeifauf Marcelo' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Pi�ero Osvaldo' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Pizi Sebastian' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Quiroga Francisco' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Raimundo Luis Francisco' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Ramos Rolando' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Randic Adrian' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Raposo luis Merlo' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Raul Vicente Villar' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Ricci Emilio' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Ricciuto Hernan' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Rigada Ramiro' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Rodriguez Danilo' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'IGNACIO' WHERE tenant_id = 3 AND legal_name ILIKE 'Rubio Ignacio' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'ROMULO' WHERE tenant_id = 3 AND legal_name ILIKE 'Rubio Romulo' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'LUCIANO' WHERE tenant_id = 3 AND legal_name ILIKE 'Rudolf Luciano' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Sanchez Adrian' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Santos Eduardo' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Sarategui Nestor' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Sarlo Gustavo' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'tambo bolivar.  Claudio' WHERE tenant_id = 3 AND legal_name ILIKE 'Sarramone Claudio' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'emanuel' WHERE tenant_id = 3 AND cuit = '20370552151' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Schestel Tabi' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Serra Martin' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Serra Maxi' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Serra Ricardo' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Gaston' WHERE tenant_id = 3 AND legal_name ILIKE 'Serrano Gaston' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Simon Oscar' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Tassara bruno' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Trillo Rodrigo' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Vaquero Juan Carlos' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Vasquez Daniel' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Vescobo Raul' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Vezzosi Marcelo' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Vicente Daniel' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Vidarloza Juan' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Villacorta Lucas' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Villar Vicente Raul' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Violini Nicolas' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Vizcaino Gustavo' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Williams Adrian' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'yanel martin' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Zinguencio Fernando' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'Zubillaga, Francisco' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'PABLO TORELLO' WHERE tenant_id = 3 AND cuit = '30518353361' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Pablo Barros' WHERE tenant_id = 3 AND cuit = '30712349359' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Norberto' WHERE tenant_id = 3 AND cuit = '23170130189' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Higueras Ricardo' WHERE tenant_id = 3 AND cuit = '33507645459' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND cuit = '30711146683' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'ARENASA JORGE' WHERE tenant_id = 3 AND cuit = '30711472556' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Rene Martineu' WHERE tenant_id = 3 AND legal_name ILIKE 'La Marukena Chica' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Hugo Libano Isaac e Hijos' WHERE tenant_id = 3 AND cuit = '30616682764' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'MAZZINI DANIEL' WHERE tenant_id = 3 AND cuit = '23297365789' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Hernan Molina' WHERE tenant_id = 3 AND legal_name ILIKE 'Molina Hernan' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'SIRI sergio' WHERE tenant_id = 3 AND legal_name ILIKE 'SIRI PEDRO' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Tu�on Sergio' WHERE tenant_id = 3 AND cuit = '30709579270' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Marchesotti Hernan' WHERE tenant_id = 3 AND legal_name ILIKE 'Orzacoa y Marchesotti' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Rodriguez Sergio' WHERE tenant_id = 3 AND legal_name ILIKE 'Rodriguez Sergio y Mariano' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Ariel Carrano' WHERE tenant_id = 3 AND legal_name ILIKE 'Carrano Ariel' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Florio Delia' WHERE tenant_id = 3 AND legal_name ILIKE 'Florio Delia y Omar' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Eitel' WHERE tenant_id = 3 AND cuit = '30711297010' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Nicolas Di Catarina' WHERE tenant_id = 3 AND cuit = '30714266566' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Pablo Carpena' WHERE tenant_id = 3 AND cuit = '27141787123' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Jorge' WHERE tenant_id = 3 AND cuit = '20104175903' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Cecilia' WHERE tenant_id = 3 AND legal_name ILIKE 'CECILIA DURISOTTI' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Guillermo' WHERE tenant_id = 3 AND cuit = '20109468976' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Armando' WHERE tenant_id = 3 AND cuit = '20169140244' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Maria Garcete' WHERE tenant_id = 3 AND cuit = '30618750058' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Maria Garcete' WHERE tenant_id = 3 AND cuit = '30519524976' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'MAXIMO MASSOLA' WHERE tenant_id = 3 AND cuit = '30712880801' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Gabriel' WHERE tenant_id = 3 AND cuit = '27039793119' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Jorge' WHERE tenant_id = 3 AND cuit = '30599608210' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Gaston' WHERE tenant_id = 3 AND cuit = '30654965273' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Sebastian' WHERE tenant_id = 3 AND cuit = '20262799051' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'LIBET' WHERE tenant_id = 3 AND cuit = '23246538204' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'sergio' WHERE tenant_id = 3 AND cuit = '27162477329' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'CARLOS RAY' WHERE tenant_id = 3 AND legal_name ILIKE 'AGROMATILDE' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Jose Luis' WHERE tenant_id = 3 AND cuit = '30711772746' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Alvaro Fidalgo' WHERE tenant_id = 3 AND cuit = '20050874029' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Jose Zabala' WHERE tenant_id = 3 AND cuit = '30715353225' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Ariel' WHERE tenant_id = 3 AND cuit = '20200348096' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Gaston Grunbaum' WHERE tenant_id = 3 AND cuit = '30715708740' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Don Otonello' WHERE tenant_id = 3 AND cuit = '33623334509' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Susana' WHERE tenant_id = 3 AND cuit = '23920005004' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Fernando Lara' WHERE tenant_id = 3 AND cuit = '30710664095' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Wenceslao' WHERE tenant_id = 3 AND legal_name ILIKE 'ROSSO PICOT WENCESLAO' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Gabriel' WHERE tenant_id = 3 AND cuit = '30509003129' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Calvo Mauricio' WHERE tenant_id = 3 AND cuit = '30616581526' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Eduardo' WHERE tenant_id = 3 AND legal_name ILIKE 'EL CALLEJON' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Gabriel' WHERE tenant_id = 3 AND cuit = '20167156429' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Martin Ayerza' WHERE tenant_id = 3 AND cuit = '30708174226' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Gonzalo y Juan' WHERE tenant_id = 3 AND cuit = '20298441056' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'diego gutierrez' WHERE tenant_id = 3 AND cuit = '30654257562' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Javier Lopez' WHERE tenant_id = 3 AND legal_name ILIKE 'El Remanso' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Simon Fourcade' WHERE tenant_id = 3 AND legal_name ILIKE 'Los Indios de Fourcade' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Nicky' WHERE tenant_id = 3 AND cuit = '30708808713' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'RAUL VESCOVO' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Roberto' WHERE tenant_id = 3 AND legal_name ILIKE 'ROBERTO FRANCO' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'El Renuevo' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'ALBERTO MORENO' WHERE tenant_id = 3 AND cuit = '20317096411' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'ANIBAL MERONI' WHERE tenant_id = 3 AND cuit = '30570797367' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'franco vizconti - gustavo portella' WHERE tenant_id = 3 AND cuit = '33710370899' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'KORGER BARBARA' WHERE tenant_id = 3 AND cuit = '30652454190' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'ANTONY JUD' WHERE tenant_id = 3 AND cuit = '30552822753' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'VACCAREZZA mariano' WHERE tenant_id = 3 AND cuit = '30711929742' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'OSVALDO ALONGE' WHERE tenant_id = 3 AND cuit = '30643770101' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'GARZARON RICARDO' WHERE tenant_id = 3 AND cuit = '30568334104' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'CHANO ARATA' WHERE tenant_id = 3 AND cuit = '20182713555' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'ARISTI ALEJO' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'JOSE MOURI�O' WHERE tenant_id = 3 AND cuit = '30559973552' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'ARNALDO APELLA' WHERE tenant_id = 3 AND cuit = '30666530469' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'NINO MUSSINI' WHERE tenant_id = 3 AND cuit = '30707408150' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'MIGUEL AVILES' WHERE tenant_id = 3 AND cuit = '20160976854' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND cuit = '30681490465' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'FABIAN RATTO' WHERE tenant_id = 3 AND cuit = '30665632489' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Boveri' WHERE tenant_id = 3 AND cuit = '33628047699' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'SEBASTIAN LARRETA' WHERE tenant_id = 3 AND cuit = '30532901738' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'SOJO SANTIAGO' WHERE tenant_id = 3 AND cuit = '30709935158' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'CHIAPPE CARLOS ALBERTO' WHERE tenant_id = 3 AND cuit = '30615638613' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Carretoni Omar' WHERE tenant_id = 3 AND cuit = '20162146867' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Carretoni claudio' WHERE tenant_id = 3 AND cuit = '20126968087' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Bernardo Bauschen' WHERE tenant_id = 3 AND cuit = '30664478451' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'CIANCIO LUCIANO RAUL' WHERE tenant_id = 3 AND cuit = '20341466548' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'CIANCIO HNOS.' WHERE tenant_id = 3 AND cuit = '30628413440' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'CIANCIO JAVIER' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'COLLA NESTOR' WHERE tenant_id = 3 AND cuit = '20050477941' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'CONSOLO ALFREDO' WHERE tenant_id = 3 AND cuit = '30547615731' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'GUSTAVO KLEIN' WHERE tenant_id = 3 AND cuit = '30508503101' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'CROCE CRISTIAN' WHERE tenant_id = 3 AND cuit = '20271010649' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Carlos Del Vigo' WHERE tenant_id = 3 AND cuit = '20252946323' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'ALEJANDRO PETEK' WHERE tenant_id = 3 AND cuit = '30621224529' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'SOFIA ARI' WHERE tenant_id = 3 AND cuit = '30511863046' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'SANTIAGO SOJO' WHERE tenant_id = 3 AND cuit = '30710233841' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'ezequiel martelli' WHERE tenant_id = 3 AND cuit = '30716375443' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'GUUYI GARCIA' WHERE tenant_id = 3 AND cuit = '30519895699' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'JOSE MOURI�O' WHERE tenant_id = 3 AND cuit = '30625359240' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Carrea Alejandro' WHERE tenant_id = 3 AND cuit = '30708456450' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'EST. RAUL MENDIZABAL SA .' WHERE tenant_id = 3 AND cuit = '30517610190' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'FERNANDO DE NEVARES' WHERE tenant_id = 3 AND cuit = '30600323357' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Tagliaferro Santiago' WHERE tenant_id = 3 AND cuit = '30696389787' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Falcomier Jose' WHERE tenant_id = 3 AND legal_name ILIKE 'Falconier Jose' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'PUENTE FERNANDO' WHERE tenant_id = 3 AND cuit = '20241598269' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'GERARDO CHIARA' WHERE tenant_id = 3 AND cuit = '30557488169' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'ANDRES MORDCOVICH' WHERE tenant_id = 3 AND cuit = '30710176538' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'GANDINI MARCELO' WHERE tenant_id = 3 AND cuit = '30582765940' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'STEIMBERG CARLOS' WHERE tenant_id = 3 AND cuit = '27051749028' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'GOBET GUILLERMO' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Elba Grossi' WHERE tenant_id = 3 AND cuit = '27049380289' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'VON GLASBERG_SHA�T' WHERE tenant_id = 3 AND cuit = '30582884478' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'BENAZO HERALDO LOS ASESORA GASTON GABILONDO' WHERE tenant_id = 3 AND cuit = '20144170882' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'JOSE MOURI�O' WHERE tenant_id = 3 AND cuit = '30708863455' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'javier iglesias' WHERE tenant_id = 3 AND cuit = '20249470539' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'DANIEL SANCHEZ .' WHERE tenant_id = 3 AND cuit = '30666460991' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'JAIME BERNASCONI' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'DIEGO GILOTAUX' WHERE tenant_id = 3 AND cuit = '20045990266' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'JUAN PEDRO ARISTI' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'KLEIN FEDERICO' WHERE tenant_id = 3 AND cuit = '20038922328' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'ROBERTO KLEIN ANTONIO' WHERE tenant_id = 3 AND cuit = '20049658363' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Bernasconi Diego' WHERE tenant_id = 3 AND cuit = '30543825944' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'JUAN FIGUERAS' WHERE tenant_id = 3 AND cuit = '30707279288' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'ANDRES MORDCOVICH' WHERE tenant_id = 3 AND cuit = '30653293247' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'FERNANDO RIVARA' WHERE tenant_id = 3 AND cuit = '30715571060' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Tomas Wyse asesor de Crhistian BENGOLEALAS CATONAS (GRIMOLDI)' WHERE tenant_id = 3 AND legal_name ILIKE 'LAS CATONAS (GRIMOLDI)' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'LLorente Jose' WHERE tenant_id = 3 AND cuit = '20041491567' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Lombardo CARLOS' WHERE tenant_id = 3 AND cuit = '20239998683' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'LOMBARDO DIEGO' WHERE tenant_id = 3 AND cuit = '20214898951' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'LOPEZ GUILLERMO' WHERE tenant_id = 3 AND cuit = '30664467433' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Manuel' WHERE tenant_id = 3 AND legal_name ILIKE 'LLORENTE LUIS' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Fernando' WHERE tenant_id = 3 AND cuit = '30708453311' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'NICOLAS FERNANDEZ LLORENTE' WHERE tenant_id = 3 AND cuit = '30716609525' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'ATILIO' WHERE tenant_id = 3 AND cuit = '30621175625' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'MARCELO MARABINI' WHERE tenant_id = 3 AND cuit = '23245502419' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'MARELLI MARINA' WHERE tenant_id = 3 AND cuit = '30709097357' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'marcos ostric' WHERE tenant_id = 3 AND cuit = '30610174295' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'CACHI' WHERE tenant_id = 3 AND cuit = '30645883221' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'JUAN WILLIS HERNAN RAMOS' WHERE tenant_id = 3 AND cuit = '30710666047' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'MENDIZABAL MATIAS' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'CARLOS LOMBARDO' WHERE tenant_id = 3 AND cuit = '30606729800' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'CALAZA RUBEN' WHERE tenant_id = 3 AND cuit = '27042371942' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'MOLEA JUAN HECTOR' WHERE tenant_id = 3 AND cuit = '20050341020' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'MOSCARDI IVAN' WHERE tenant_id = 3 AND cuit = '30679473448' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'MAURO ALARCON' WHERE tenant_id = 3 AND cuit = '30607597193' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Mariano Newton' WHERE tenant_id = 3 AND cuit = '20242702264' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Osvaldo Odello' WHERE tenant_id = 3 AND cuit = '20123609248' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'ORLANDO ARRECHEA' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'FRAN LALOR' WHERE tenant_id = 3 AND cuit = '30615603364' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'PALAY HECTOR' WHERE tenant_id = 3 AND cuit = '20172415580' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'STEIMBERG CARLOS' WHERE tenant_id = 3 AND cuit = '30709675628' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'MATIAS CULLEN' WHERE tenant_id = 3 AND cuit = '30707272029' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'ANIBAL MERONI' WHERE tenant_id = 3 AND cuit = '30652983908' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'JOSE' WHERE tenant_id = 3 AND cuit = '20050330517' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'PECORELLI POCHO' WHERE tenant_id = 3 AND cuit = '20147766131' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'LA PONTEZUELA .' WHERE tenant_id = 3 AND cuit = '30511593170' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'estevan vaccarezza' WHERE tenant_id = 3 AND cuit = '20237118007' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'RATO DIEGO' WHERE tenant_id = 3 AND cuit = '20130557474' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'ROCCA GERMAN' AND company_type = 'prospect';
UPDATE companies SET trade_name = '�' WHERE tenant_id = 3 AND legal_name ILIKE 'ROCCA MAXI' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'RODRIGUES MIGUEL ANGEL' WHERE tenant_id = 3 AND cuit = '20120982819' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Andres Rossi' WHERE tenant_id = 3 AND legal_name ILIKE 'Rossi Andres' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Javier Capra' WHERE tenant_id = 3 AND cuit = '30707878025' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'BERTOLACCI ROXANA' WHERE tenant_id = 3 AND cuit = '30508446329' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Aristi Osvaldo' WHERE tenant_id = 3 AND cuit = '27180859530' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'MATIAS PINCIROLLI' WHERE tenant_id = 3 AND cuit = '30658668508' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'SBERNA ROBERTO' WHERE tenant_id = 3 AND cuit = '30593121727' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Anibal Bravo Garcia' WHERE tenant_id = 3 AND cuit = '30707533117' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'SOUBELET ROBERTO' WHERE tenant_id = 3 AND cuit = '20264921636' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Kevin Casey' WHERE tenant_id = 3 AND cuit = '30712045007' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'FERNANDO SPELANZON' WHERE tenant_id = 3 AND cuit = '20146025928' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'ALVARO TOMAS' WHERE tenant_id = 3 AND cuit = '30709596078' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'TERPOLILLI NORBERTO' WHERE tenant_id = 3 AND cuit = '20050519008' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'FRAN BAUSCHEN' WHERE tenant_id = 3 AND cuit = '30715442872' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'ALDO ALDABE' WHERE tenant_id = 3 AND cuit = '33707833799' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Klein Gustavo' WHERE tenant_id = 3 AND cuit = '27118060054' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Abel Marchione' WHERE tenant_id = 3 AND cuit = '30658938300' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'VACCAREZZA MIGUEL ANGEL' WHERE tenant_id = 3 AND cuit = '30666525554' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Hernan Vazquez' WHERE tenant_id = 3 AND legal_name ILIKE 'Vazquez Hernan' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'ROBERTO KLEIN' WHERE tenant_id = 3 AND cuit = '30527480171' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Mariano VIDANO' WHERE tenant_id = 3 AND cuit = '30664465902' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'ALEJANDRO' WHERE tenant_id = 3 AND legal_name ILIKE 'Vita Alejandro' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'Gobet Guillermo' WHERE tenant_id = 3 AND cuit = '20165794800' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'YA�EZ JOS� LUIS' WHERE tenant_id = 3 AND cuit = '20050412920' AND company_type = 'prospect';
UPDATE companies SET trade_name = 'JUAN ZLATAR' WHERE tenant_id = 3 AND cuit = '20172415882' AND company_type = 'prospect';
