UPDATE companies SET phone = '2342401835', email = 'administracion@soldohue.com.ar' WHERE tenant_id = 3 AND legal_name = 'AGRICOLA ANDIFE SRL / ALEJANDRO ROMEO' AND company_type = 'client';
UPDATE companies SET phone = '2342412167', email = 'mgbruinin@hotmail.com' WHERE tenant_id = 3 AND legal_name = 'BECARIA JORGE A. Y BRUININ MARIA G.' AND company_type = 'client';
UPDATE companies SET phone = '2346412301', email = 'Bergamini.aldo.2016@gmail.com' WHERE tenant_id = 3 AND legal_name = 'BERGAMINI ALDO RUBEN' AND company_type = 'client';
UPDATE companies SET email = 'administracion@soldohue.com.ar' WHERE tenant_id = 3 AND legal_name = 'BLANCO MIGUEL ANGEL' AND company_type = 'client';
UPDATE companies SET phone = 'VENDIDO 12 BLS DE 1153 IG' WHERE tenant_id = 3 AND legal_name = 'Lopez Mazzini' AND company_type = 'client';
UPDATE companies SET email = 'mariomartin2@hotmail.com' WHERE tenant_id = 3 AND legal_name = 'MAZZINI MARIO MARTIN' AND company_type = 'client';
UPDATE companies SET email = 'javiermosca40@gmail.com' WHERE tenant_id = 3 AND legal_name = 'Mosca Javier Gustavo' AND company_type = 'client';
UPDATE companies SET phone = '3462-567929' WHERE tenant_id = 3 AND legal_name = 'AGROALMERIA' AND company_type = 'client';
UPDATE companies SET phone = '2314-622233' WHERE tenant_id = 3 AND legal_name = 'Alfonso Osvaldo' AND company_type = 'client';
UPDATE companies SET phone = '2314-500901' WHERE tenant_id = 3 AND legal_name = 'Algarra Gaston' AND company_type = 'client';
UPDATE companies SET phone = '249-4643452' WHERE tenant_id = 3 AND legal_name = 'Azcarete Aldo' AND company_type = 'client';
UPDATE companies SET phone = '2314-535688' WHERE tenant_id = 3 AND legal_name = 'Ballestero Martin' AND company_type = 'client';
UPDATE companies SET phone = '2314-533539' WHERE tenant_id = 3 AND legal_name = 'Borghi Adolfo' AND company_type = 'client';
UPDATE companies SET phone = '2314-416184' WHERE tenant_id = 3 AND legal_name = 'Braida Agustin' AND company_type = 'client';
UPDATE companies SET phone = '2344-443356' WHERE tenant_id = 3 AND legal_name = 'Bustingorri Goncho' AND company_type = 'client';
UPDATE companies SET phone = '2314-409142' WHERE tenant_id = 3 AND legal_name = 'Calvo Mauricio' AND company_type = 'client';
UPDATE companies SET phone = '11-5408-0171' WHERE tenant_id = 3 AND legal_name = 'Canepa Ignacio' AND company_type = 'client';
UPDATE companies SET phone = '11-6024-0529' WHERE tenant_id = 3 AND legal_name = 'Capelle Juan Martin' AND company_type = 'client';
UPDATE companies SET phone = '11-5006-9535' WHERE tenant_id = 3 AND legal_name = 'Caruzo Enzo' AND company_type = 'client';
UPDATE companies SET phone = '2314-579707' WHERE tenant_id = 3 AND legal_name = 'Castelani Osvaldo' AND company_type = 'client';
UPDATE companies SET phone = '2342-407834' WHERE tenant_id = 3 AND legal_name = 'Celerino Jeronimo' AND company_type = 'client';
UPDATE companies SET phone = '2396-614685' WHERE tenant_id = 3 AND legal_name = 'Coll Irene' AND company_type = 'client';
UPDATE companies SET phone = '2392-510873' WHERE tenant_id = 3 AND legal_name = 'Maria teresa' AND company_type = 'client';
UPDATE companies SET phone = '11-3088-1041' WHERE tenant_id = 3 AND legal_name = 'Cosentino Gustavo y Santoro Julio' AND company_type = 'client';
UPDATE companies SET phone = '11-6661-3953' WHERE tenant_id = 3 AND legal_name = 'Durrieu Dolores' AND company_type = 'client';
UPDATE companies SET phone = '11-5021-7796' WHERE tenant_id = 3 AND legal_name = 'Eduardo Gallo Llorente' AND company_type = 'client';
UPDATE companies SET phone = '2314-441015' WHERE tenant_id = 3 AND legal_name = 'El pecan' AND company_type = 'client';
UPDATE companies SET phone = '2314-401127' WHERE tenant_id = 3 AND legal_name = 'Fernandez Guillermo' AND company_type = 'client';
UPDATE companies SET phone = '2314-628017' WHERE tenant_id = 3 AND legal_name = 'Francisqueli Dario' AND company_type = 'client';
UPDATE companies SET phone = '11-5007-3353' WHERE tenant_id = 3 AND legal_name = 'Goldscheidt Juan' AND company_type = 'client';
UPDATE companies SET phone = '2314-448136' WHERE tenant_id = 3 AND legal_name = 'Gutierrez Francisco' AND company_type = 'client';
UPDATE companies SET phone = '2314-401805' WHERE tenant_id = 3 AND legal_name = 'Gutierrez Manuel' AND company_type = 'client';
UPDATE companies SET phone = '2396-548269' WHERE tenant_id = 3 AND legal_name = 'Hollman santiago' AND company_type = 'client';
UPDATE companies SET phone = '2314-530741' WHERE tenant_id = 3 AND legal_name = 'Iturriaga Ignacio' AND company_type = 'client';
UPDATE companies SET phone = '11-5656-0878' WHERE tenant_id = 3 AND legal_name = 'La solita' AND company_type = 'client';
UPDATE companies SET phone = '2314-627043' WHERE tenant_id = 3 AND legal_name = 'Lagreca Anibal' AND company_type = 'client';
UPDATE companies SET phone = '2392-536915' WHERE tenant_id = 3 AND legal_name = 'PAPA Y CHICOS' AND company_type = 'client';
UPDATE companies SET phone = '2314-621193' WHERE tenant_id = 3 AND legal_name = 'LA ESPERANZA' AND company_type = 'client';
UPDATE companies SET phone = '2284-587883' WHERE tenant_id = 3 AND legal_name = 'Mendia Alejandro' AND company_type = 'client';
UPDATE companies SET phone = '2392-489219' WHERE tenant_id = 3 AND legal_name = 'Monasterio Ruben' AND company_type = 'client';
UPDATE companies SET phone = '(310) 292-4783' WHERE tenant_id = 3 AND legal_name = 'Ocampo Rafael' AND company_type = 'client';
UPDATE companies SET phone = '2396-440680' WHERE tenant_id = 3 AND legal_name = 'EL broquel' AND company_type = 'client';
UPDATE companies SET phone = '2314-625137' WHERE tenant_id = 3 AND legal_name = 'Peierguidi Juan' AND company_type = 'client';
UPDATE companies SET phone = '11-65597186' WHERE tenant_id = 3 AND legal_name = 'Pereyra Iraola Ignacio Coco' AND company_type = 'client';
UPDATE companies SET phone = '2284-217257' WHERE tenant_id = 3 AND legal_name = 'Preisegger Juan' AND company_type = 'client';
UPDATE companies SET phone = '11-6600-7171' WHERE tenant_id = 3 AND legal_name = 'Pulgari Marcelo' AND company_type = 'client';
UPDATE companies SET phone = '2314-514780' WHERE tenant_id = 3 AND legal_name = 'Ima sumac' AND company_type = 'client';
UPDATE companies SET phone = '2314-620606' WHERE tenant_id = 3 AND legal_name = 'Sanchez German' AND company_type = 'client';
UPDATE companies SET phone = '11-5739-9647' WHERE tenant_id = 3 AND legal_name = 'Sanchez Lama Ricardo' AND company_type = 'client';
UPDATE companies SET phone = '2314-408905' WHERE tenant_id = 3 AND legal_name = 'Santamaria Matias' AND company_type = 'client';
UPDATE companies SET phone = '11-5457-8666' WHERE tenant_id = 3 AND legal_name = 'Santoro Julio' AND company_type = 'client';
UPDATE companies SET phone = '2396-634571' WHERE tenant_id = 3 AND legal_name = 'Sarciat Martin' AND company_type = 'client';
UPDATE companies SET phone = '11-3781-7964' WHERE tenant_id = 3 AND legal_name = 'Stefoni Marcelo' AND company_type = 'client';
UPDATE companies SET phone = '2314-620105' WHERE tenant_id = 3 AND legal_name = 'Valerga Hector.' AND company_type = 'client';
UPDATE companies SET phone = '2314-476631' WHERE tenant_id = 3 AND legal_name = 'Vicente Santiago' AND company_type = 'client';
UPDATE companies SET phone = '2395-407244' WHERE tenant_id = 3 AND legal_name = 'Zabala Jose Luis' AND company_type = 'client';
UPDATE companies SET phone = '249-446-9404' WHERE tenant_id = 3 AND legal_name = 'FMT Lacteos SA' AND company_type = 'client';
UPDATE companies SET phone = '2396-519372' WHERE tenant_id = 3 AND legal_name = 'Lena SCA' AND company_type = 'client';
UPDATE companies SET phone = '2923-563436' WHERE tenant_id = 3 AND legal_name = 'Delfinagro SA' AND company_type = 'client';
UPDATE companies SET phone = '11-5463-5782' WHERE tenant_id = 3 AND legal_name = 'Rangi Agropecuaria' AND company_type = 'client';
UPDATE companies SET phone = '2396-448023' WHERE tenant_id = 3 AND legal_name = 'Ronzitti Ruben Genaro' AND company_type = 'client';
UPDATE companies SET phone = '11-5001-3819' WHERE tenant_id = 3 AND legal_name = '4 leguas' AND company_type = 'client';
UPDATE companies SET phone = '2346682454' WHERE tenant_id = 3 AND legal_name = 'ABETEC SOCIEDAD ANONIMA' AND company_type = 'client';
UPDATE companies SET email = '"csoler@soldohue.com.ar' WHERE tenant_id = 3 AND legal_name = 'AGRAR AGRICOLA ARGENTINA S A' AND company_type = 'client';
UPDATE companies SET email = 'federicoalfaro20@yahoo.com.ar' WHERE tenant_id = 3 AND legal_name = 'ALFARO EDUARDO FEDERICO' AND company_type = 'client';
UPDATE companies SET phone = '2923445394' WHERE tenant_id = 3 AND legal_name = 'ARANA RAUL ALBERTO' AND company_type = 'client';
UPDATE companies SET phone = '2346682454' WHERE tenant_id = 3 AND legal_name = 'WILSON JORGE' AND company_type = 'client';
UPDATE companies SET phone = '2358405185' WHERE tenant_id = 3 AND legal_name = 'AVILEZ MARIANO / AVILES RAUL' AND company_type = 'client';
UPDATE companies SET phone = '2342401274', email = 'mlbagattin@gmail.com' WHERE tenant_id = 3 AND legal_name = 'BAGATTIN MAURICIO LUCAS' AND company_type = 'client';
UPDATE companies SET phone = '2346569272', email = 'bbauschen@hotmail.com' WHERE tenant_id = 3 AND legal_name = 'BAUSCHEN BERNARDO' AND company_type = 'client';
UPDATE companies SET phone = '2346655522', email = 'administracion@soldohue.com.ar' WHERE tenant_id = 3 AND legal_name = 'CHIARA GERARDO' AND company_type = 'client';
UPDATE companies SET email = 'lseran@full-agro.com.ar' WHERE tenant_id = 3 AND legal_name = 'FULL AGRO S.A.' AND company_type = 'client';
UPDATE companies SET phone = '234251222', email = 'hcolombo@crebragado.com.ar' WHERE tenant_id = 3 AND legal_name = 'HUGO COLOMBO SA' AND company_type = 'client';
UPDATE companies SET phone = '2364419231' WHERE tenant_id = 3 AND legal_name = 'JOSE RICARDO KLIN' AND company_type = 'client';
UPDATE companies SET phone = '2364659343' WHERE tenant_id = 3 AND legal_name = 'MOLEA JORGE Y RAUL' AND company_type = 'client';
UPDATE companies SET phone = '02364-585427' WHERE tenant_id = 3 AND legal_name = 'NATERO CINTIA VANESA' AND company_type = 'client';
